[metadata]
name = desisim
version = attr: desisim.__version__
author = DESI Collaboration
author_email = desi-data@desi.lbl.gov
license = BSD-3-Clause
license_files = LICENSE.rst
url = https://github.com/desihub/desisim
description = DESI simulation package
long_description = file: README.rst
long_description_content_type = text/x-rst
edit_on_github = True
github_project = desihub/desisim
classifiers =
    Development Status :: 4 - Beta
    Environment :: Console
    Intended Audience :: Science/Research
    License :: OSI Approved :: BSD License
    Operating System :: OS Independent
    Programming Language :: Python :: 3
    Topic :: Scientific/Engineering :: Astronomy
    Topic :: Utilities

[options]
zip_safe = False
package_dir =
    =py
# find_namespace avoids a warning about data directories when building packages.
packages = find_namespace:
include_package_data = True
python_requires = >=3.10
install_requires =
    numpy
    astropy
    scipy
    fitsio
    matplotlib
    healpy
    pyyaml
    speclite
    specsim>=1.0.0
    desiutil
    desitarget
    desimodel
    desispec
#     # Don't forget to install desimodel test data.
#     # specter is not on PyPI under that name: the `specter` project there is an
#     # unrelated BDD testing library, while DESI's specter also declares the
#     # name `specter`, so it has to come from git.
#     git+https://github.com/desihub/specter.git@main#egg=specter
#     # simqso is not on PyPI, and its install script requires numpy, so install
#     # it separately.
#     git+https://github.com/imcgreer/simqso.git@v1.2.4#egg=simqso

[options.extras_require]
all =
test =
    pytest
coverage =
    pytest-cov
    coveralls
doc =
    Sphinx
    sphinx-rtd-theme

[options.package_data]
desisim =
    data/*
desisim.test =
    data/*
    data/maps/*
    data/surveyops/ops/*

[options.packages.find]
where = py
exclude = .github/*

[tool:pytest]
testpaths = py

[coverage:run]
relative_files = True
source =
    py/desisim
omit =
    py/desisim/_version.py
    py/desisim/conftest*
    py/desisim/test/*
    py/desisim/*/test/*
    */desisim/_version.py
    */desisim/conftest*
    */desisim/test/*
    */desisim/*/test/*

[coverage:report]
exclude_lines =
    # Have to re-enable the standard pragma
    pragma: no cover
    # Don't complain about packages we have installed
    except ImportError
    # Don't complain if tests don't hit assertions
    raise AssertionError
    raise NotImplementedError
    # Ignore branches that don't pertain to this version of Python
    pragma: py{ignore_python_version}
    # Don't complain about IPython completion helper
    def _ipython_key_completions_

[pycodestyle]
# See https://pycodestyle.readthedocs.io/en/latest/intro.html#configuration
# for details of these configuration options.
#
# These are normally ignored by default:
# ignore = E121, E123, E126, E133, E226, E241, E242, E704, W503, W504
#
# In addition to the default set we add:
# - E501: line too long (82 > 79 characters)
# - E731: do not assign a lambda expression, use a def
# - E741: do not use variables named 'l', 'O', or 'I' -- because, for example,
#   'l' might refer to Galactic longitude.
ignore = E121, E123, E126, E133, E226, E241, E242, E501, E704, E731, E741, W503, W504
